[build-system]
requires = ["hatchling>=1.32.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/py_pinyin_split/__about__.py"

[project]
name = "py-pinyin-split"
dynamic = ["version"]
description = 'Library for splitting Hanyu Pinyin phrases into all valid syllable combinations'
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE.txt"]
keywords = ['chinese', 'pinyin']
authors = [
    { name = "lstrobel", email = "mail@lstrobel.com" },
    { name = "Thomas Lee", email = "thomaslee@throput.com" },
]
maintainers = [{ name = "lstrobel", email = "mail@lstrobel.com" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    'Intended Audience :: Developers',
    'Operating System :: OS Independent',
    'Topic :: Text Processing :: Linguistic',
    'Topic :: Utilities',
]
dependencies = ["marisa-trie>=1.4.1", "nltk>=3.10.3"]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest-benchmark>=5.3.0",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]

[project.urls]
Documentation = "https://github.com/lstrobel/py-pinyin-split#readme"
Issues = "https://github.com/lstrobel/py-pinyin-split/issues"
Source = "https://github.com/lstrobel/py-pinyin-split"

[tool.uv]
exclude-newer = "3 days"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
